name: gym
description: A new Flutter project.

dependencies:
  font_awesome_flutter: 6.0.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: "^3.0.2"                                       # new                                   # new
  firebase_auth: "^0.5.5"                                           # new

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/rohan.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/banner.png
    - assets/images/poster.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/ellie.png
    - assets/images/eric.png
    - assets/images/jenny.png
    - assets/images/kevin.png
    - assets/images/louis.png
    - assets/images/ruppee.png